site_name: Sunk Costs
repo_url: https://github.com/sunkcosts
repo_name: sunkcosts

plugins:
- search

theme:
  name: material
  custom_dir: overrides
  logo: assets/logos/miamilost-logo-small.png
  favicon: assets/logos/miamilost-logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
  - header.autohide
  - navigation.instant
  - navigation.tracking

extra_css:
- stylesheets/extra.css

markdown_extensions:
- md_in_html
- admonition
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true

nav:
- Analysis:
  - Abstract: "index.md"
  - EarthShade: "earthshade.md"
  - Contact: "contact.md"
