site_name: Sunk Costs

plugins:
- search
- glightbox

theme:
  name: material
  custom_dir: overrides
  logo: assets/logos/sunk-costs-logo-small.png
  favicon: assets/logos/sunk-costs-logo-small.png
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
  - header.autohide
  - navigation.instant
  - navigation.tracking
  # - navigation.tabs
  - content.code.copy

extra_css:
- stylesheets/extra.css

markdown_extensions:
- md_in_html
- admonition
- attr_list
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true

nav:
- About: "index.md"
# - Report: "report.md"
# - Model: "model/note.md"
# - Conference: "conference.md"
# - Resources: "resources.md"
# - References: references.md"
- Contact: "contact.md"
