site_name: Sunk Costs

plugins:
- search

theme:
  name: material
  custom_dir: overrides
  logo: assets/logos/github.png
  favicon: assets/logos/sunkcosts-logo-small.png
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
  - header.autohide
  - navigation.instant
  - navigation.tracking

extra_css:
- stylesheets/extra.css

markdown_extensions:
- md_in_html
- admonition
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true

nav:
- About: "index.md"
# - EarthShade: "earthshade.md"
# - Contact: "contact.md"
