site_name: Sunk Costs

plugins:
- search

theme:
  name: material
  custom_dir: overrides
  logo: assets/logos/sunk-costs-logo-small.png
  favicon: assets/logos/sunk-costs-logo-small.png
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
  - header.autohide
  - navigation.instant
  - navigation.tracking
  - navigation.tabs

extra_css:
- stylesheets/extra.css

markdown_extensions:
- md_in_html
- admonition
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true

nav:
- About: "index.md"
- Report:
  - Introduction: "report/introduction.md"
- Resource:
  - Index: "resource/index.md"
  - Conference: "resource/conference.md"
  - Model: "resource/model.md"
  - Repository: "resource/repository.md"
  - Dataset: "resource/dataset.md"
- Reference:
  - Index: "reference/index.md"
  - Publication: "reference/publication.md"
  - Dataset: "reference/dataset.md"
  - Package: "reference/package.md"
  - Service: "reference/service.md"
  - Tool: "reference/tool.md"
- Contact: "contact.md"
