
site_name: Sunk Costs
docs_dir: website
site_url: https://sunkcosts.github.io

theme:
  name: material
  favicon: "file/internal/image.logo.sunkcosts.png"
  logo: "file/internal/anim.logo.fast.gif"
  logo_url: "/"
  logo_tooltip: ""
  custom_dir: website/static/custom
  icon:
    annotation: material/plus-circle
  font:
    text: Inter
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
  - search.suggest
  - content.code.copy
  - content.code.annotate
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.indexes
  - navigation.top
  - navigation.expand
  - navigation.instant

plugins:
- search
# - roamlinks
- mkdocstrings
- mkdocs-jupyter:
    include_source: false
    include_requirejs: true
- glightbox:
    skip_classes:
    - skip-lightbox

markdown_extensions:
- attr_list
- md_in_html
- admonition
- footnotes
- mkdocs-click
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format



extra:
  generator: false
  quicklinks:
  - name: Model
    info: Open interactive model.
    icon: lucide/orbit
    link: https://sunkcosts.streamlit.app
  - name: Repository
    info: View source code.
    icon: lucide/fingerprint
    link: https://github.com/sunkcosts/sunkcosts.github.io
  - name: Improvement
    info: Suggest an improvement.
    icon: lucide/lightbulb
    link: https://github.com/sunkcosts/sunkcosts.github.io/discussions

extra_css:
- static/styles/theme.css
- static/styles/admonition.css

extra_javascript:
# - static/script/tabs.js
# - static/script/search.js
- static/script/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
- Analysis: analysis.md
- Documentation:
  - documentation/index.md
  - Setup: documentation/setup.md
  - Usage: documentation/usage.md
  - Structure: documentation/structure.md
  - CLI: documentation/cli.md
  - Notebook:
    - Historical SLR: documentation/notebook/global_slr_trends.ipynb
# - Approach:
#   - approach/index.md
#   - approach/global_slr_trends.ipynb
# - Notebook:
#   - notebook/index.md
# - Notes:
#   - ""
# - Jupyter:
#   - ""
# - Test: notebook/index.md
# - Test: notebook/index.md
# - Test: notebook/index.md
# - Test: notebook/index.md
# - Test: notebook/index.md
# - Test: notebook/index.md
# - Test: notebook/index.md
# - Model: "https://www.google.com"
# - Report: "report.md"
# - Model: "model/note.md"
# - Conference: "conference.md"
# - Resources: "resources.md"
# - References: references.md"
# - Contact: "contact.md"
# - About: "index.md"
# - Research:
#   - Table of Contents: "research/00.table_of_contents.md"
#   - Introduction: "research/01.introduction.md"
#   - Qualitative Analysis: "research/02.analysis.md"
#   - "Methodology: Project Cost": "research/03.methodology.01.project.md"
#   - "Methodology: Opportunity Cost": "research/03.methodology.01.cost.md"
#   - "Results: Project Cost": "research/04.results.01.project.md"
#   - "Results: Opportunity Cost": "research/04.results.01.cost.md"
#   - Discussion: "research/05.discussion.md"
#   - References: "research/06.references.md"
#   - Appendix: "research/07.appendix.md"
# - Documentation:
#   - Requirements: "documentation/00.requirements.md"
#   - Installation: "documentation/01.installation.md"
#   - Tutorial: "documentation/02.tutorial.md"
#   - Features: "documentation/03.features.md"
