
site_name: Sunk Costs
docs_dir: report
site_url: https://sunkcosts.github.io

nav:
- index.md

theme:
  name: material
  favicon: "file/site/image.logo.sunkcosts.png"
  logo: "file/site/anim.logo.fast.gif"
  logo_url: "/"
  logo_tooltip: ""
  custom_dir: report/static/custom
  icon:
    annotation: material/plus-circle
  font:
    text: Inter
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
  - search.suggest
  - content.code.copy
  - content.code.annotate
  - navigation.tracking

plugins:
- search
- roamlinks
- glightbox:
    effect: fade
    skip_classes:
    - skip-lightbox
- mkdocs-jupyter:
    theme: dark
    include_source: false
    include_requirejs: true
    show_input: false
    no_input: True
    remove_tag_config:
      remove_input_tags:
      - hide

markdown_extensions:
- attr_list
- md_in_html
- admonition
- footnotes
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format



extra:
  generator: false
  quicklinks:
  - name: GitHub Organization
    info: Source Code & Resources
    icon: lucide/fingerprint
    link: https://github.com/sunkcosts
    # - name: Streamlit App
    #   info: Interactive Model
    #   icon: lucide/orbit
    #   link: https://sunkcosts.streamlit.app
    # - name: Author Website
    #   info: Author Information
    #   icon: lucide/at
    #   link: https://harttraveller.com


extra_css:
- static/styles/global.admonition.css
- static/styles/global.notebook.css
- static/styles/global.theme.css
- static/styles/max.theme.css
- static/styles/med.theme.css
- static/styles/min.theme.css
- static/styles/testing.css
# - static/styles/theme.old.css

extra_javascript:
# - static/script/tabs.js
- static/script/quicklink.js
# - static/script/video.js
# - static/script/video-test.js
- static/script/search.js
- static/script/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


